# Commands to start on workspace startup
tasks:
  - init: install laraboot cli
    command: npm i @laraboot-io/cli
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview