# Commands to start on workspace startup
workspaceLocation: laraboot-vercel-demo/src
tasks:
  - name: Install cli
    init: npm i -g @laraboot-io/cli
    command: |
      cd /workspace/laraboot-vercel-demo/src
      laraboot --version
      laraboot task add nodejs --imageUri=gcr.io/paketo-buildpacks/nodejs --format=external
      laraboot task add @core/laravel-foundation-provider --format=file -vvv
      laraboot task add @core/laravel-config --format=file -vvv
      laraboot task add @core/laravel-model-views --format=file -vvv
      laraboot task add @core/laravel-starterkit-buildpack --format=file -vvv
      laraboot task add @core/laraboot-packer --format=file -vvv
      laraboot task add @core/laraboot-hook-before-pack --format=file -vvv
      laraboot build dev -vvv --pack-params default-process=task
      laraboot run
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview