# Commands to start on workspace startup
tasks:
  - init: Build app
    command: |
    npm i @laraboot-io/cli
    laraboot init --name=app --description="Simple App" --php-version="8.0.*"
    laraboot task add nodejs --imageUri=gcr.io/paketo-buildpacks/nodejs --format=external
    laraboot task add @core/laravel-foundation-provider --format=file -vvv
    laraboot task add @core/laravel-config --format=file -vvv
    laraboot task add @core/laravel-model --format=file -vvv
    laraboot task add @core/laravel-model-views --format=file -vvv
    laraboot task add @core/laravel-starterkit-buildpack --format=file -vvv
    laraboot task add @core/laraboot-packer --format=file -vvv
    laraboot task add @core/laraboot-hook-before-pack --format=file -vvv
    DEBUG=* laraboot build dev -vvv --pack-params default-process=task || true
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview