# Commands to start on workspace startup
workspaceLocation: src
tasks:
  - init: Install cli
    command: npm i -g @laraboot-io/cli
  - command: laraboot task add nodejs --imageUri=gcr.io/paketo-buildpacks/nodejs --format=external
  - command: laraboot task add @core/laravel-foundation-provider --format=file -vvv
  - command: laraboot task add @core/laravel-config --format=file -vvv
  - command: laraboot task add @core/laravel-model-views --format=file -vvv
  - command: laraboot task add @core/laravel-starterkit-buildpack --format=file -vvv
  - command: laraboot task add @core/laraboot-packer --format=file -vvv
  - command: laraboot task add @core/laraboot-hook-before-pack --format=file -vvv
  - command: laraboot build dev -vvv --pack-params default-process=task
  - command: laraboot run
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview