# Commands to start on workspace startup
workspaceLocation: laraboot-vercel-demo/src
tasks:
  - name: Install cli
    openMode: tab-after
    init: npm i -g @laraboot-io/cli
    command: |
      laraboot --version
      cd /workspace/laraboot-vercel-demo/src
      mkdir -p ~/.local/share/ && cp laraboot.json ~/.local/share/laraboot.json
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
